### ISSUE TITLE
Create Initial VentureTutor Environment

### ISSUE THREAD

**Issue by Ofthemasses** [Ofthemasses/VentureTutor#1]
## Description
ReinforcementLearning.jl environments are in essence the simulation state. It provides agents with observations and rewards and allows the agent to perform actions in this environment. The following will explain what the first iteration of the AI will entail.

### Training data and Goal
The goal of the AI is to modify a code document so that it matches another document in Vim. To initialize the training data we will do the following:
- Accumulate code documents written in the same language. The language is yet to be decided, but will be a scripted language.
- Create copies of each document and pair them. Document A & Document B.
- Document A will be manually modified to include a unique corruption of data.
- Split these document pairs into a 4:1 ratio train test split.

### Creating the environment
An environment will include the following variables
- Vim text stream of Document A.
- Vim text stream of Document B, with the same view as Document A.

The AI can enter keyboard characters as an input, with a few omitted e.g. `:` to avoid the AI using plugins or exiting vim.
The AI will be rewarded for matching Document B and Document A. The reward will be higher if the total input count is low.

### Training the model
The training for this environment will be primitive, using the predefined agents in ReinforcementLearning.jil. The goal of this issue is primarily to setup the basics of the VentureTutor Environment, and get a handle on how to do Reinforcement Learning with Julia.

## To-Do
- [x] Create the environment
  - [x] Create initial environment structure
  - [x] Generate and read vim instances
- ~~Train the model on one document pair and adjust~~
- ~~Train the model on ten documents pairs with a 4:1 train test split~~
- [X] Do a brief clean up of the code
